Audit and make documentation for command GETEX consistent
DiceDB/dice pull request #1099
Opened 2024-10-15 12:46 UTC by AbhirajPatwa

Audited GETEX documentation to be consistent to redis

2024-10-15 12:57 UTC, AbhirajPatwa commented
For issue #821

2024-10-17 07:33 UTC, apoorvyadav1111 requested changes
Hi, Thanks for making all of these changes. I have left few comments.

2024-10-17 07:33 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/GETEX.md
> +127.0.0.1:7379> GETEX mykey EXAT 1672531199
```suggestion
127.0.0.1:7379> GETEX mykey EXAT 1672531199
127.0.0.1:7379> "Hello"
```

2024-10-17 07:33 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/GETEX.md
> +127.0.0.1:7379> GETEX mykey PXAT 1672531199000
```suggestion
127.0.0.1:7379> GETEX mykey PXAT 1672531199000
127.0.0.1:7379> "Hello"
```

2024-10-17 07:33 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/GETEX.md
> +127.0.0.1:7379> GETEX mykey PX 10000
```suggestion
127.0.0.1:7379> GETEX mykey PX 10000
127.0.0.1:7379> "Hello"
```

2024-10-17 07:33 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/GETEX.md
> +127.0.0.1:7379> GETEX mykey EX 10
```suggestion
127.0.0.1:7379> GETEX mykey EX 10
127.0.0.1:7379> "Hello"
```

2024-10-17 07:33 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/GETEX.md
> +127.0.0.1:7379> GETEX mykey PERSIST
```suggestion
127.0.0.1:7379> GETEX mykey PERSIST
127.0.0.1:7379> "Hello"
```

2024-10-17 07:33 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/GETEX.md
> +## Examples
Let's keep it consistent with what we have in other docs. In future, we can rename all of them in one PR to make them consistent. 
```suggestion
## Example Usage
```

2024-10-17 10:41 UTC, AbhirajPatwa commented
Added your part, should we merge now?

2024-10-17 11:17 UTC, apoorvyadav1111 approved these changes
Thanks for the changes, Approved.

2024-10-17 11:17 UTC, merged