Fix LPOP to support multiple arguments #1100
DiceDB/dice pull request #1105
Opened 2024-10-15 20:04 UTC by tren03

This pull request addresses issue #1100, where the LPOP command needed to support an additional argument to specify the number of elements to pop from the left side of the list.

Changes:
Modified the LPOP command to accept either 1 or 2 arguments:
LPOP key: Pops a single element from the list (default behavior).
LPOP key count: Pops up to count elements from the list.

Validation:
If count is 0, an empty response is returned.

If count is negative, an "out of range" error is returned.
If count exceeds the number of available elements, it pops as many elements as available without error.
Invalid count (non-integer values) returns an appropriate error.
Popping from a non-existent or empty list returns nil.

Behavior:
Returns a single element if one element is popped.
Returns a list of elements if multiple elements are popped.

This is the dicedb output 
![dice-output](https://github.com/user-attachments/assets/91370ac3-22d2-43fb-819e-4dc95f8d2cc3)

This is the output for redis over the same commands
![redis-output](https://github.com/user-attachments/assets/2b0bf251-cbe3-425a-b088-e15d97fae8a4)

2024-10-16 12:32 UTC, JyotinderSingh requested changes
Thanks for the fix! It would be great to have unit and integration tests validating these changes.

2024-10-16 12:43 UTC, tren03 commented
> Thanks for the fix! It would be great to have unit and integration tests validating these changes.

Thanks :), Yep I am on it.

2024-10-16 16:43 UTC, tren03 commented
this is the unit-tests
![unittest](https://github.com/user-attachments/assets/495b0f51-1ec5-46b0-8f60-614196f94991)

this is the integration tests
![integrationtest](https://github.com/user-attachments/assets/a2dbd40b-79cb-4d35-a3f6-f645f91689c4)

any changes to make?

2024-10-25 03:28 UTC, tren03 commented
Hey,
Its been a while since I heard back.
I saw that there was a slight conflict with my branch, so i fixed it with a merge.
Would love to get some updates on this issue.

2024-10-29 13:04 UTC, JyotinderSingh commented
> Hey, Its been a while since I heard back. I saw that there was a slight conflict with my branch, so i fixed it with a merge. Would love to get some updates on this issue.

whoops, didn't realise the comments were addressed. Going through this PR.

2024-10-29 13:08 UTC, JyotinderSingh requested changes
Thanks for these changes @tren03! The implementation in itself looks solid, have left a few minor comments.

2024-10-29 13:08 UTC, JyotinderSingh commented on internal/eval/eval_test.go
> +	testEvalLPOP(t, store)
Looks like we are calling `testEvalLPOP` twice here.

2024-10-29 13:08 UTC, JyotinderSingh commented on integration_tests/commands/async/deque_test.go
We need to add similar tests to HTTP and Websocket directory as well. As a part of this exercise it would be great if you could help verify that the rest of the tests in this file are also replicated there.

2024-10-29 13:14 UTC, tren03 commented on integration_tests/commands/async/deque_test.go
For the LPOP tests right?

2024-10-30 07:58 UTC, tren03 commented on integration_tests/commands/async/deque_test.go
> Hey, I was working on porting the tests to http and websockets directory. I noticed that the http server returns a float for LPUSH, where as localhost operation returns an integer. Is this expected behaviour?
![2024-10-30-132701_1166x219_scrot](https://github.com/user-attachments/assets/4441cf21-85b6-41a1-936f-b7b2bd4e6023)

2024-11-01 14:13 UTC, closed without merging

2024-11-01 14:39 UTC, tren03 commented on integration_tests/commands/async/deque_test.go
I did a mistake, and pushed into the wrong branch
This is my first so a bit nervous
I did the requested changes.
Could I still contribute?