Audited Copy command for docs consistency
DiceDB/dice pull request #1140
Opened 2024-10-18 11:25 UTC by onlybond

This PR closes Issue : #816 

Have changed the docs to be consistent and used  [SET Command docs](https://dicedb.io/commands/set/) for reference 

Do lemme know if there are any changes to be done

2024-10-18 15:44 UTC, apoorvyadav1111 commented
Hi @onlybond , Thanks for the changes. DiceDB currently does not support databases hence the argument destination db is not being used by the server. A user can pass the parameter, It will be ignored. Therefore, please update any such reference where it is mentioned that the destination key will be updated in the destination DB. 
Thanks

2024-10-19 04:24 UTC, onlybond commented
Hey @apoorvyadav1111 , Thanks for reviewing the PR, As you said DiceDB doesn't support databases, so in the docs should i remove all the references which are related to db? So in the parameters only 3 parameters will be given as of now?

2024-10-19 05:48 UTC, apoorvyadav1111 commented
So you can remove references which mention that the key will be inserted in database, You can mention in the description about this. But please take that as an argument as we do take it as an argument, but just ignore it. It act as sort of placeholder.

2024-10-20 09:55 UTC, apoorvyadav1111 requested changes
Hi, we have created referenced for documentation for easy reference and consistency which can found here: docs/command_docs_template.md and docs/sample_command_docs.md

2024-10-22 07:38 UTC, apoorvyadav1111 commented
Hi @onlybond, Hope you are well. I am eager to know more about your progress on this issue. Please reach out to me if you need any clarifications.

2024-10-23 09:00 UTC, onlybond commented
hello @apoorvyadav1111 I have mentioned about the the key to be stored in another database in the notes. until diceDB supports databases its viable to mention it in the notes section.

2024-10-23 10:16 UTC, apoorvyadav1111 requested changes
Hi, Thanks for making the changes. Please align the Error sections to the template.
Thanks,
Apoorv

2024-10-24 05:17 UTC, onlybond commented
hi there I have made the changes. please have a review on it.

2024-10-24 09:43 UTC, apoorvyadav1111 requested changes
left one minor comment. I think we are good to go after this change

2024-10-24 09:43 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/COPY.md
> +    - This error occurs if the destination key already exists and the `REPLACE` option is not specified.
```suggestion
1. `Wrong type of value or key`:
    - Error message `(error) WRONGTYPE Operation against a key holding the wrong kind of value`:
    - This error occurs if the source key holds a value that is not compatible with the `COPY` operation.
2.  `Not existent key`:
    -  Error message: `(error) ERR no such key` 
    - This error occurs if the source key does not exist.
```

2024-10-24 10:22 UTC, onlybond commented
All changes done. LGTM

2024-10-24 10:23 UTC, apoorvyadav1111 approved these changes

2024-10-24 10:23 UTC, merged