fix: issue #1115 handling integer parsing in SETBIT in certain situation
DiceDB/dice pull request #1155
Opened 2024-10-19 13:41 UTC by kaushal-003

This PR closes issue #1115:
### Description:

- Updated `ByteSliceToObj` function to handle integer parsing more robustly. If the modified byte array can't be parsed as an integer, it now defaults to a string format(similar to how redis handles it).
- added corresponding unit test with expected output.

2024-10-19 17:57 UTC, apoorvyadav1111 requested changes
Blocking merge until #1017 is closed.
Thanks

2024-11-17 07:49 UTC, JyotinderSingh commented
@apoorvyadav1111 is this PR unblocked now?

2024-11-17 17:02 UTC, apoorvyadav1111 commented
Yes @JyotinderSingh , we can merge this now

2024-11-17 17:04 UTC, JyotinderSingh commented
@kaushal-003 please rebase on the latest master

2024-11-19 10:39 UTC, kaushal-003 commented
Sure, will do it by tonight.

2024-11-25 08:55 UTC, kaushal-003 commented
@JyotinderSingh  Done rebasing

2024-11-26 23:27 UTC, apoorvyadav1111 requested changes
Can we please add tests for this functionality?

2024-12-01 07:37 UTC, kaushal-003 commented
@apoorvyadav1111 added a testcase.

2024-12-01 18:19 UTC, merged