Changed scope of CmdWatchSubscriptionChan to local
DiceDB/dice pull request #1169
Opened 2024-10-20 18:48 UTC by KanniShashankh

it's not global anymore, this might be a noobish implemention tho, i'm open for advice on how to implement it in a better way. Thanks!

Fixes https://github.com/DiceDB/dice/issues/1000
CmdWatchSubscriptionChan shouldn't be a global variable

2024-10-20 18:50 UTC, KanniShashankh commented
also, i think my linter might be misconfigured or something, the diff shows extra lines touched. :(

2024-10-21 17:55 UTC, KanniShashankh commented
am i missing something here? i'll fix the linter ci run fail but for the integration tests. it fails for even the base branch? is there some config that i'm missing?
<img width="1501" alt="Screenshot 2024-10-21 at 11 25 27 PM" src="https://github.com/user-attachments/assets/d679e53a-ced8-4da9-8b43-c9ffd64c0d33">

2024-10-22 12:07 UTC, JyotinderSingh commented
Looks like you may have messed up the merge with master. Usually, you want to:
1. update your local master with the upstream `git checkout master && git pull upstream`
2. checkout your feature branch `git checkout <branch name>
3. merge with master `git merge master`
4. push `git push`

2024-10-22 12:13 UTC, JyotinderSingh requested changes
Thanks for this contribution @KanniShashankh! The changes look good overall, have left a few minor comments.

2024-10-22 12:13 UTC, JyotinderSingh commented on integration_tests/commands/resp/setup.go
> +	)
declare this in the same manner as the queryWatchChan and cmdWatchChan to maintain consistency. Ideally these definitions should be clubbed together.

2024-10-22 12:13 UTC, JyotinderSingh commented on internal/server/httpServer.go
you can remove these changes as they are unrelated.

2024-10-22 12:13 UTC, JyotinderSingh commented on internal/server/websocketServer.go
undo this unrelated change.

2024-10-22 12:13 UTC, JyotinderSingh commented on internal/watchmanager/watch_manager.go
> +		cmdWatchSubscriptionChan chan WatchSubscription
We can add a comment here explaining the purpose of this channel, same as the other members of this struct.

2024-10-29 13:23 UTC, merged