Issue-1103 - Fixing broken pipe errors
DiceDB/dice pull request #1170
Opened 2024-10-20 23:12 UTC by Kannav02

The identification of broken pipe is only when there is an abrupt exit, so what I saw in the codebase was there are only a couple of places that deal with the closure of WebSocket connections, most of them were only handling the case where the user exited irrespective if it was gracefully or abruptly, so I modified and added some sections for the same

- in the `closing_handshake` , it wasn't checking if the closeValue had an error, indicating that there was an error while closing the connection, so I added a check for the same
- now when a message is being read, if there is an error that belongs to the `errs` category, it means that there is a graceful exit, otherwise, the exit was due to another error, so I have added the check for the same
- In the `WriteResponseWithRetries` you have a case where the function returns the `syscall.EPIPE` error, this function is utilized in WebSocketHandler function, so I have added the check for the same

Those were all the that i found were capable of returning broken pipe errors, i have provided the segregated messages for the same, please do let me know if any other changes or features are needed

Fixes #1103 

Thank you!

2024-10-21 05:45 UTC, JyotinderSingh commented
Thanks for this contribution, please fix the lint errors and merge conflicts

2024-10-21 13:23 UTC, Kannav02 commented
Hey @JyotinderSingh!

Sure, i would resolve the merge conflicts, however I believe the linting errors existed even before I tried to make any change as they are in files different to the one I had made changes to, I don't want to break the codebase

2024-10-22 18:59 UTC, Kannav02 commented
I have rebased the branch again to follow the linear path for the new master branch with merged PRs.

2024-10-24 09:22 UTC, JyotinderSingh requested changes
Thanks for these changes. Left a couple of comments.

2024-10-24 09:22 UTC, JyotinderSingh commented on internal/server/websocketServer.go
> +				slog.Info("Gracefully Exited")
This doesn't need to be logged.

2024-10-24 09:22 UTC, JyotinderSingh commented on internal/server/websocketServer.go
> +			slog.Info("graceful shutdown...")
This does not need to be logged.

2024-10-24 09:22 UTC, JyotinderSingh commented on internal/server/websocketServer.go
> +			slog.Warn("Error during closing handshake", slog.Any("error", closeErr))
Make this a debug log.

2024-10-26 12:25 UTC, JyotinderSingh approved these changes
LGTM. Thanks for this contribution!

2024-10-26 12:25 UTC, merged