FIX: SET Command Inconsistency
DiceDB/dice pull request #1215
Opened 2024-10-28 17:42 UTC by vanshavenger

<img width="802" alt="Screenshot 2024-10-28 at 11 09 33 PM" src="https://github.com/user-attachments/assets/2d83175b-074a-490a-80bd-c67d24d86acb">

The above was not same in the Current Dice db implementation , i have fixed it, kindly verify once and let me know if there is something that is need to be change and updated too.

It makes it consistent with current DOCs and Redis Implementation.  
#786
cc @apoorvyadav1111

2024-10-29 13:38 UTC, JyotinderSingh commented
Please add testsbto validate these changes

2024-10-29 15:53 UTC, vanshavenger commented
Sure will do....

2024-10-29 19:15 UTC, lucifercr07 requested changes
LGTM, please add tests.

2024-10-29 19:15 UTC, lucifercr07 commented on internal/eval/store_eval.go
@vanshavenger Shall we add unit/integration for this?

2024-10-29 20:37 UTC, vanshavenger commented on internal/eval/store_eval.go
Adding Integration test so that it will be tested against all cases. 
PR Coming in Sometime.

2024-10-29 20:54 UTC, vanshavenger commented
@lucifercr07 added tests that were missing and now it is consistent with the DICE DB Sets docs too and Also with redis.

2024-10-30 10:45 UTC, lucifercr07 approved these changes

2024-10-30 10:46 UTC, merged