feat: Add a tutorial example for URL Shortner built using DiceDB and Go
DiceDB/dice pull request #1259
Opened 2024-11-09 14:00 UTC by Prachi-Jamdade

This commit adds an example of how to integrate the DiceDB Go SDK for building a URL shortener application. 

The tutorial walks through setting up a basic URL shortening service, providing - 
1. Instructions on creating short URLs
2. Redirecting to the original URLs
3. Storing data in DiceDB. 

The application utilizes the `Set` and `Get` commands from DiceDB to store and retrieve shortened URLs, and the example is designed to help developers quickly understand and implement a URL shortener using DiceDB and Go.

2024-11-09 16:16 UTC, JyotinderSingh requested changes
Thanks for contributing a tutorial for dicedb. It's a great way to help new users get started.

I have left some comments on this PR, please address them.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +   git clone https://github.com/Prachi-Jamdade/url-shortner-go-dicedb
Two things,

1. The examples should allow users to have a super minimal setup to try stuff out. Ideally, they should not require much setup so they don't need to clone repositories to get started.
2. We shouldn't be linking personal repositories in the official docs. If you would like to make the code available to the users you can add it under the examples directory of this repo.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +1. *Start DiceDB*: Ensure DiceDB is running.
DiceDB is expected to be running since we already mention that above.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +## Interacting with the application
This section should come in the end.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +Syntax - `Set(key, value, expiration)`
```suggestion
```go
dicedb.Set(key, value, expiration)
```
```

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +`value`: The data to store (serialized JSON)
```suggestion
`value`: The data to store (complete URL)
```

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +- `utils`: Provides helper functions for API responses.
This is too complicated for a tutorial. This app can be built within a single file and that's what we should prefer.

The motivation here is to provide users with the most basic, unopinionated code which they can then adapt to their own projects. This tutorial should ideally keep the entire code contained within a single file.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +    }
we don't need to define a model here. The key can be the short URL, the value can be the long URL.
Again, this tutorial should have the most basic setup (no need to think too deeply about extensibility)

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +    }
Based on above comments this can be simplified down to just a couple of lines of code. All it needs to do is store short URLs mapped to long URLs.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +    }
Based on above comments this can be simplified down to just a couple of lines of code. All it needs to do is lookup keys by short URL.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +    }
no need to have "services" here. Just direct SDK calls from within the go application are enough.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +    ```
no need to have this in a separate package/file. the actual code these functions encapsulate is simpler to understand at first glance as compared to hiding them behind an abstraction

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +6. `main.go`: Sets up the Gin (a HTTP Web Framework) router and registers routes. This is the entry point of the application.
Please have the entire code for the application contained within `main.go`.

2024-11-09 16:16 UTC, JyotinderSingh commented on docs/src/content/docs/get-started/url-shortner.mdx
> +
We can remove this.
```suggestion
```

2024-11-09 17:48 UTC, Prachi-Jamdade commented
Hi @JyotinderSingh, I have addressed above mentioned review changes and pushed the code. 

Please take a look at it.

2024-11-11 02:49 UTC, everlearner reviewed
Minor comments in the shortener code.

2024-11-11 02:49 UTC, everlearner commented on examples/url-shotener/main.go
nit: typo in directory name `url-shortner`

2024-11-11 02:49 UTC, everlearner commented on examples/url-shotener/main.go
> +		Addr: "localhost:7379",
Get hostname and port from ENV variables?
Similar to: https://github.com/DiceDB/dice/blob/44779c2b0763eecfcf869a79d5936f013e4422e7/examples/leaderboard-go/main.go#L36-L44

2024-11-11 02:49 UTC, everlearner commented on examples/url-shotener/main.go
> +func CreateShortURL(c *gin.Context) {
nit: camel case?
```suggestion
func createShortURL(c *gin.Context) {
```

2024-11-11 02:49 UTC, everlearner commented on examples/url-shotener/main.go
> +func RedirectURL(c *gin.Context) {
nit:
```suggestion
func redirectURL(c *gin.Context) {
```

2024-11-11 02:53 UTC, everlearner commented on examples/url-shotener/main.go
> +	requestBody.ShortURL = "http://localhost:8080/" + shortID
Do we need to store `ID` and `ShortURL` in the struct?
Having just `LongURL` is sufficient?

The mapping b/w `ID` and `LongURL` is anyway stored in the DiceDB.

2024-11-13 15:57 UTC, JyotinderSingh commented
Thanks for addressing the comments @Prachi-Jamdade. Could you please resolve comments by @everlearner as well?

2024-11-14 17:11 UTC, Prachi-Jamdade commented
Hey @JyotinderSingh, pushed the code addressing changes raised by @everlearner

2024-11-14 18:53 UTC, everlearner approved these changes
Thanks for making the changes.

2024-11-16 14:09 UTC, Prachi-Jamdade commented
Hey @JyotinderSingh, any update ?

2024-11-19 14:24 UTC, JyotinderSingh commented
> Hey @JyotinderSingh, any update ?

Will review soon

2024-11-20 16:35 UTC, JyotinderSingh requested changes
Thanks for addressing the reviews so far @Prachi-Jamdade. Documentation is a critical aspect of any project, and needs to be extremely polished. Keeping that in mind I've suggested some improvements.

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +2. DiceDB server running locally
```suggestion
1. Go (version 1.18 or later): [Download Go](https://golang.org/dl/)
2. DiceDB: A DiceDB server running locally. Refer to the [DiceDB Installation Guide](https://github.com/DiceDB/dice/pull/1259/get-started/installation) if you haven't set it up yet.
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +`key`: The identifier for the data to retrieve.
```suggestion
## Understanding DiceDB Commands

We'll use the following DiceDB commands:

### `SET` Command

Stores a key-value pair in DiceDB.

- **Syntax**: `SET key value [expiration]`
  - `key`: Unique identifier (e.g., short URL code)
  - `value`: Data to store (e.g., serialized JSON)
  - `expiration`: Optional; time-to-live in seconds (use `0` for no expiration)

### `GET` Command

Retrieves the value associated with a key.

- **Syntax**: `GET key`
  - `key`: Identifier for the data to retrieve
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +## Code overview
```suggestion
## Writing the Code

Create a file named `main.go` and add the following code:
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +## Explanation of Key Parts
```suggestion
## Explanation
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +4. Starting the Server: The `main` function starts the Gin server on port `8080`.
We should make use of subheadings to make this clearer. PTAL at the following approach to write this:
```suggestion

### 1. Initialize the DiceDB Client

We set up the DiceDB client in the `init` function:

    ```go
db = dicedb.NewClient(&dicedb.Options{
    Addr: "localhost:7379",
})
    ```

### 2. Create Short URL Endpoint

- **Input Validation**: Ensures the `long_url` field is present.
- **Short ID Generation**: Uses `uuid` to create a unique 8-character ID.
- **Data Serialization**: Converts the `URL` struct to JSON.
- **Data Storage**: Saves the JSON data in DiceDB with the `Set` command.
- **Response**: Returns the generated short URL.

### 3. Redirect to Original URL Endpoint

- **Data Retrieval**: Fetches the URL data from DiceDB using the `Get` command.
- **Data Deserialization**: Converts JSON back to the `URL` struct.
- **Redirection**: Redirects the user to the `LongURL`.

### 4. Start the Server

The `main` function sets up the routes and starts the server on port `8080`.
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +## Starting the application server
```suggestion
## Running the Application

### 1. Start the Go Application
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +1. Start DiceDB: Ensure DiceDB is running.
```suggestion
### 2. Ensure DiceDB is Running

Ensure your DiceDB server is up and running on port `7379`.
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +2. Test the API:
```suggestion
## Testing the Application

```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +        ```
```suggestion
**Using `curl`:**

    ```bash
curl -X POST -H "Content-Type: application/json" -d '{"long_url": "https://example.com"}' http://localhost:8080/shorten
    ```

**Response:**

    ```json
{
  "short_url": "http://localhost:8080/<short ID generated by the server>"
}
    ```
```

2024-11-20 16:35 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +        ```
```suggestion
**Using `curl`:**

    ```bash
curl -L http://localhost:8080/abcd1234
    ```

**Using a Browser:**

Navigate to:

    ```
http://localhost:8080/abcd1234
    ```

You should be redirected to `https://example.com`.
```

2024-11-20 16:35 UTC, JyotinderSingh commented on examples/url-shortener/.dockerignore
This file is not needed.

2024-11-20 16:35 UTC, JyotinderSingh commented on examples/url-shortener/Dockerfile
We don't need such a detailed dockerfile, the following is fine:
```dockerfile
# Build Stage
FROM golang:1.23 AS builder

WORKDIR /app

# Copy go.mod and go.sum to download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy application source code and build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

# Runtime Stage
FROM alpine:latest

# Install runtime dependencies
RUN apk --no-cache add ca-certificates

# Copy the built application
WORKDIR /root/
COPY --from=builder /app/server .

# Expose the application port
EXPOSE 8080

# Start the application
CMD ["./server"]

```

2024-11-20 16:36 UTC, JyotinderSingh commented on docs/src/content/docs/tutorials/url-shortener.md
> +    ```
```suggestion
### 1. Install and Run DiceDB

Start a DiceDB server using Docker:

    ```bash
docker run -d -p 7379:7379 dicedb/dicedb
    ```

This command pulls the DiceDB Docker image and runs it, exposing it on port `7379`.

### 2. Initialize a New Go Project

Create a new directory for your project and initialize a Go module:

    ```bash
mkdir url-shortener
cd url-shortener
go mod init url-shortener
    ```

### 3. Install Required Packages

Install the DiceDB Go SDK and other dependencies:

    ```bash
go get github.com/dicedb/dicedb-go
go get github.com/gin-gonic/gin
go get github.com/google/uuid
    ```
```

2024-11-25 17:09 UTC, JyotinderSingh commented
@Prachi-Jamdade hope you are doing well, are you actively working on this PR?

2024-11-25 17:14 UTC, Prachi-Jamdade commented
Hey @JyotinderSingh, yes I'll push changes by tomorrow morning.

Got stuck in end sem exams. I'll address them quickly.

2024-11-25 17:17 UTC, JyotinderSingh commented
> Hey @JyotinderSingh, yes I'll push changes by tomorrow morning.
> 
> 
> 
> Got stuck in end sem exams. I'll address them quickly.

Thanks for the update! No rush.

2024-12-05 18:02 UTC, JyotinderSingh commented
Thanks for making the changes @Prachi-Jamdade. The code looks good, and it is easy to follow the tutorial.

However, I am noticing that the tutorial is not appearing anywhere in the side navigation on the website. I can only access it by specifically searching for it in the search bar. I've added a commit for the same.

2024-12-05 18:04 UTC, JyotinderSingh approved these changes
LGTM

2024-12-05 18:05 UTC, merged