migration: json-numincrby-nummultby-toggle-forget-del and add integration testcases
DiceDB/dice pull request #1261
Opened 2024-11-09 15:56 UTC by vpsinghg

This PR includes changes for migration of `JSON.DEL`, `JSON.FORGET`, `JSON.TOGGLE`, `JSON,NUMINCRBY` and `JSON.NUMMULTBY` command to new `Eval` method. 
This resolves issue #1029 

Also introduces fix for `oom` err in `resp` protocol integration test on lower spec machines.

Improved Integration Test format.

Tasks Checklist
 
- [x] Migrated the evalXXX function with the latest definition
- [x] Update or add unit tests for the new implementation.
- [x] All unit tests pass successfully.
- [x] Ensure all integration tests pass successfully.

2024-11-09 16:10 UTC, vpsinghg commented
@AshwinKul28 @ayadav16 @lucifercr07 
`make test` all integration passing on local but failing in CI pipeline

2024-11-09 16:48 UTC, apoorvyadav1111 commented
Hi @vpsinghg , Just to confirm, Have you rebased this with the latest master?

2024-11-09 17:04 UTC, vpsinghg commented
Yes, No conflicts as I have created new branch and added my changes.

2024-11-09 17:07 UTC, apoorvyadav1111 reviewed
Woah! Amazing work. Looking forward to take these changes to master soon. Meanwhile I have left few comments. Please check

2024-11-09 17:07 UTC, apoorvyadav1111 commented on internal/server/cmd_meta.go
> +	jsontoggleCmdMeta = CmdsMeta{
Lets keep the naming convention consistent here with other json commands. for ex `jsonForgetCmdMeta` .

2024-11-09 17:07 UTC, apoorvyadav1111 commented on testutils/json.go
I guess we can use assert.ElementsMatch instead of manually checking permutaitions of array now that we are using new package for asserts

2024-11-09 17:08 UTC, apoorvyadav1111 requested changes
edit: requesting changes, could'nt edit previous comment

2024-11-09 17:09 UTC, vpsinghg commented on integration_tests/commands/resp/setup.go
> +	config.DiceConfig.Memory.KeysLimit = 2000
Yes, O.w.  integration test for resp fails on lower spec machines.

2024-11-09 17:11 UTC, vpsinghg commented on integration_tests/commands/async/json_test.go
Okay

2024-11-09 17:18 UTC, apoorvyadav1111 commented
@vpsinghg , checks are okay now, I guess we just need to update some minor details and we are good to close this.

2024-11-09 17:21 UTC, apoorvyadav1111 commented on integration_tests/commands/resp/setup.go
> +	config.DiceConfig.Memory.KeysLimit = 2000
Okay, could you please leave a comment here mentioning why we have to make this change?
```go
// #1261 : Adding this here because ..... 
```

2024-11-10 04:03 UTC, vpsinghg commented
@apoorvyadav1111 changes done. and check is also successful. Please go ahead

2024-11-12 08:45 UTC, vpsinghg commented
@apoorvyadav1111 please review

2024-11-12 11:27 UTC, merged