Adds support for SMEMBERS.WATCH command
DiceDB/dice pull request #1289
Opened 2024-11-16 14:04 UTC by superiorsd10

This PR implements the feature described in the issue #1132. The new `SMEMBERS.WATCH` command allows subscribed clients to receive push responses whenever the data in a respective set is modified. 

---

### Changed Introduced

- Modified the `evalSADD` function
- Added command constants
- Updated command watch manager
- Defined metadata for `SMEMBERS.WATCH`
- Added integration tests

---

### Why did I modified the `evalSADD` function

I have had to modify this function because the subscribers were receiving double notifications for the first `SADD` command. The old implementation caused double notifications because it performed a `store.PUT` for the initial set creation and subsequent additions. The new implementation defers the `store.PUT` operation until all additions are complete, ensuring subscribers are notified only once. 

### Why Sorting the Results in Integration Tests Is Necessary

To validate the correctness of the reactive system, we care about the contents and not the order of the set. Sorting both the expected and received results allows us to 

- Ignore the effects of the asynchronous delivery.
- Focus solely on whether the correct data was transmitted.

---

### Screenshot

![SCR-20241116-q7s](https://github.com/user-attachments/assets/f369b259-157a-4a0a-862e-824a893c556b)

2024-11-17 06:42 UTC, JyotinderSingh reviewed
Thanks for adding support for `SMEMBERS.WATCH` command @superiorsd10! Had a few small comments.

2024-11-17 06:42 UTC, JyotinderSingh commented on internal/eval/store_eval.go
Could you reformat this file? I'm seeing additional diffs here due to indentation changes which makes it harder to see the actual code changes.

2024-11-17 06:42 UTC, JyotinderSingh commented on integration_tests/commands/resp/smemberswatch_test.go
> +func sortSlice(v any) any {
Do we really need to use sortSlice? I think we may be able to use testify library's `assert.ElementsMatch` method

2024-11-17 06:43 UTC, JyotinderSingh requested changes
Requested changes.

2024-12-06 02:21 UTC, apoorvyadav1111 commented
Hi @superiorsd10 , Please rebase the PR with latest master, Thanks.

2024-12-24 16:41 UTC, superiorsd10 commented
@apoorvyadav1111 I've rebased it with the latest master. Thank you!

2025-01-08 17:49 UTC, lucifercr07 commented
@superiorsd10 apologies for delayed review. There's a conflict if you can rebase. Meanwhile will go through PR for review. Thanks for contributing.

2025-01-11 05:26 UTC, superiorsd10 commented
@JyotinderSingh @lucifercr07 I've rebased it. Please review.

2025-03-20 11:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DiceDB/dice?pullRequest=1289) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DiceDB/dice?pullRequest=1289) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DiceDB/dice?pullRequest=1289) it.</sub>

2025-04-29 18:24 UTC, arpitbbhayani commented
this is obsolete now. Closing the PR to keep things clean. Thanks for working on the patch.

2025-04-29 18:24 UTC, closed without merging