changes for issue 1114
DiceDB/dice pull request #1296
Opened 2024-11-19 05:29 UTC by Yashasv-Prajapati

This PR closes #1114.

2024-11-19 05:32 UTC, Yashasv-Prajapati commented
Hey @apoorvyadav1111, could you please take a look at it and approve.

2024-11-20 20:57 UTC, apoorvyadav1111 requested changes
Thanks for this fix, have left some comments.

2024-11-20 20:57 UTC, apoorvyadav1111 commented on integration_tests/commands/async/bit_test.go
Please add tests in resp, websocket, and HTTP folder. We are migrating away from asyncserver.

2024-11-22 16:22 UTC, Yashasv-Prajapati commented on integration_tests/commands/async/bit_test.go
hey, done as asked, please take a look and let me know

2024-11-22 17:45 UTC, apoorvyadav1111 approved these changes
Thanks for adding tests. will merge once checks are ✅

2024-11-22 17:54 UTC, merged