Add hyperlink for mentioned commands in command documentation
DiceDB/dice pull request #1325
Opened 2024-11-23 09:40 UTC by pankajjs

## Issue Number
 - Closes #1324 

## Description
 - This PR adds hyperlink for mentioned commands in the command documentation for easily navigation.

2024-11-23 13:15 UTC, pankajjs commented
@lucifercr07 @apoorvyadav1111 Could you please review this PR?

2024-11-23 16:56 UTC, apoorvyadav1111 requested changes
Hi, thanks for raising a PR so quickly, I have left comments, please check. In addition to the comments, I would say not adding any new section but hyperlink the ones in the existing document unless there is no mention of the alternative commands. Additionally lets add customized text in the section than "Please check ... for more information" as this conveys that the link contains more information related to the command page we are at. 

Documentation are essential artifacts for a user to adopt a product and hence the review can sound more like a nit, However, lets add  the changes which conveys the message in the best possible way.
Thanks

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/BITFIELD_RO.md
>  - Read-only variant of the BITFIELD command. It is like the original BITFIELD but only accepts GET subcommand.
```suggestion
- Read-only variant of the BITFIELD command. It is like the BITFIELD but only accepts GET subcommand.
```

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/BITFIELD_RO.md
> +- See original [BITFIELD](/commands/bitfield) for more details.
```suggestion
- See [BITFIELD](/commands/bitfield) for more details.
```

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/COMMAND HELP.md
> +The `COMMAND HELP` command outputs help text that lists all the available subcommands for the `COMMAND` command. It is used to understand how each subcommand functions and the available options for t
```suggestion
The `COMMAND HELP` command outputs help text that lists all the available subcommands for the [`COMMAND`](/commands/command) command. It is used to understand how each subcommand functions and the available options for those subcommands.
```

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/DECR.md
> +- Please refer to the [DECRBY](/commands/decrby) command documentation for more information.
We can add the information in the Alternatives section and add the hyperlink as follows:
[`DECRBY`](/commands/decrby)

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/EXPIRE.md
> +- Please refer to the [TTL](/commands/ttl), [PERSIST](/commands/persist) and [EXPIREAT](/commands/expireat)  commands documentation for more information.
same as above. Lets add the infomation in Alternatives section. Also lets keep the style as [`TTL`](...URL..)

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/EXPIREAT.md
> +- Please refer to the [TTL](/commands/ttl), [PERSIST](/commands/persist) and [EXPIRE](/commands/expire)  commands documentation for more information.
same as above. Lets have this information in Alternatives section.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/EXPIRETIME.md
> +- Please refer to the [TTL](/commands/ttl) and [PTTL](/commands/pttl) commands documentation for more information.
same as above. Lets add the information in Alternatives section.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/HEXISTS.md
> +- Please refer to the [HGET](/commands/hget) command documentation for more information.
same as above. Lets add the information in Alternatives section and style as discussed above.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/HINCRBY.md
> +- Please refer to the [HINCRBYFLOAT](/commands/hincrbyfloat) command documentation for more information.
```suggestion
- DiceDB also supports [`HINCRBYFLOAT`](/commands/hincrbyfloat) command for incrementing float values. 
```

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/HINCRBYFLOAT.md
> +- Please refer to the [HGET](/commands/hget), [HSET](/commands/hset) and [HINCRBY](/commands/hincrby) commands documentation for more information.
not needed

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/HKEYS.md
> +- Please refer to the [HGETALL](/commands/hgetall) command documentation for more information.
same as above. Lets add the information in the Alternatives section and style as discussed above.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/HRANDFIELD.md
> +- Please refer to the [HEXISTS](/commands/hexists), [HKEYS](/commands/hkeys) and [HSCAN](/commands/hscan) commands documentation for more information.
not needed

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/HVALS.md
> +- Please refer to the [HGETALL](/commands/hgetall) command documentation for more information.
same as above. Lets add the information in Alternatives section and style as discussed above.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/INCR.md
> +- Please refer to the [DECR](/commands/decr), [INCRBY](/commands/incrby) and [INCRBYFLOAT](/commands/incrbyfloat) commands documentation for more information.
```suggestion
```
same as above. Lets add the information in Alternatives section and style as discussed above.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/LINSERT.md
> +- Please refer to the [RPUSH](/commands/rpush), [LPUSH](/commands/lpush), [LPOP](/commands/lpop) and [RPOP](/commands/rpop) commands documentation for more information.
same as above. Lets add the information in the Best Practices section and style as discussed above.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/LLEN.md
> +- Please refer to the [RPUSH](/commands/rpush), [LPUSH](/commands/lpush), [LPOP](/commands/lpop) and [RPOP](/commands/rpop) commands documentation for more information.
same as above. Lets add the information in the Best Practices section and style as discussed above.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/LPOP.md
> +- Please refer to the [RPUSH](/commands/rpush), [LPUSH](/commands/lpush), [LLEN](/commands/llen) and [RPOP](/commands/rpop) commands documentation for more information.
same as above

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/LPUSH.md
> +- Please refer to the [RPUSH](/commands/rpush), [LPOP](/commands/lpop), [LLEN](/commands/llen) and [RPOP](/commands/rpop) commands documentation for more information.
same as above

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/LRANGE.md
> +- Please refer to the [RPUSH](/commands/rpush), [LPUSH](/commands/lpush), [LPOP](/commands/lpop) and [RPOP](/commands/rpop) commands documentation for more information.
same as above

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/PTTL.md
> +- Please refer to the [EXPIRE](/commands/expire) and [TTL](/commands/ttl) commands documentation for more information.
same as above. Lets add the information in Alternatives section and style as discussed above.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/RPOP.md
> +
Lets add the hyperlinks the existing text.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/RPUSH.md
> +- Please refer to the [RPOP](/commands/rpop), [LLEN](/commands/llen), [LPOP](/commands/lpop) and [LPUSH](/commands/lpush) commands documentation for more information.
Lets add the hyperlinks to the existing text.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/SMEMBERS.md
> +5. Please refer to the [EXISTS](/commands/exists) command documentation for more information
```suggestion
```

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/SMEMBERS.md
> +5. Please refer to the [EXISTS](/commands/exists) command documentation for more information
Lets add the hyperlinks to the existing text.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/TTL.md
> +## Notes
Lets add the hyperlinks to the existing text.

2024-11-23 16:56 UTC, apoorvyadav1111 commented on docs/src/content/docs/commands/ZRANK.md
> +- Please refer to the [ZADD](/commands/zadd) command documentation for more information.
Lets add the hyperlinks to the existing text.

2024-11-25 08:05 UTC, pankajjs commented
@apoorvyadav1111 Removed new section and added the hyperlink in existing commands. Could you please review it?

2024-11-25 13:52 UTC, apoorvyadav1111 approved these changes
Thank you for this enhancement.

2024-11-25 13:52 UTC, merged