Support JSON.ARRINDEX #486
DiceDB/dice pull request #1348
Opened 2024-11-30 15:45 UTC by iamskp11

Implements #486.

2024-12-03 03:49 UTC, iamskp11 commented on internal/eval/store_eval.go
> +	// 0 or -1 means the last element is included.
ToDo: Modify this to correct comment.

2024-12-03 03:49 UTC, iamskp11 commented on internal/eval/store_eval.go
> +		return diceerrors.NewErrWithMessage("object with key does not exist")
ToDo: Match with dicedb output

2024-12-03 03:50 UTC, iamskp11 commented on internal/eval/store_eval.go
> +		return diceerrors.NewErrWithMessage("invalid JSONPath")
ToDo: Match with dicedb output

2024-12-08 02:54 UTC, apoorvyadav1111 approved these changes

2024-12-08 02:55 UTC, apoorvyadav1111 requested changes
Could you please also add documentation for this new command?

Thanks,
Apoorv

2024-12-08 22:02 UTC, apoorvyadav1111 commented
Hi @iamskp11, I reran the CI for the PR. Also, I would like to request to change the permutation function in other two files as well.

Thanks

2024-12-09 23:39 UTC, apoorvyadav1111 commented
Hi @iamskp11 , thanks for these changes. Could you please rebase the PR? I can merge once the CI checks are passed.

2024-12-09 23:40 UTC, apoorvyadav1111 approved these changes

2024-12-10 01:03 UTC, iamskp11 commented
@apoorvyadav1111  Pls do not merge. Getting some issues related to HTTP tests since cmd_meta.go is deleted in latest master. Will debug and fix today later.

2024-12-16 16:25 UTC, JyotinderSingh commented
> @apoorvyadav1111 Pls do not merge. Getting some issues related to HTTP tests since cmd_meta.go is deleted in latest master. Will debug and fix today later.

Hi @iamskp11, did you get a chance to address the issues?

2024-12-17 03:21 UTC, iamskp11 commented
> > @apoorvyadav1111 Pls do not merge. Getting some issues related to HTTP tests since cmd_meta.go is deleted in latest master. Will debug and fix today later.
> 
> Hi @iamskp11, did you get a chance to address the issues?

Hi @JyotinderSingh , thanks for reminding.
Sorry, wasn't able to prioritise it last week. This is fixed, and tests are passing.
But, it failed Github check here, "context cancelled" issue. Can you re-run the tests?

2024-12-21 02:58 UTC, apoorvyadav1111 commented
Hi @iamskp11 , Is this PR ready for review and merge? Please confirm

2024-12-21 11:41 UTC, iamskp11 commented
> Hi @iamskp11 , Is this PR ready for review and merge? Please confirm

Yes @apoorvyadav1111 , this is ready for review, merge. Have added latest changes.

2024-12-21 19:57 UTC, merged