New WAL implementation with configurable variables
DiceDB/dice pull request #1356
Opened 2024-12-03 07:09 UTC by ayushsatyam146

Fixes https://github.com/DiceDB/dice/issues/1285
It is a new WAL implementation based on the decided configurable values. This doesn't contain support for checkpointing and recovery yet. Appropriate TODO markers are there for checkpointing and recovery.
Previous iteration of basic Benchmark
![image](https://github.com/user-attachments/assets/1bc25e0f-6fbc-4930-9f18-44c5a6184f34)
New interaction of basic benchmark
![image](https://github.com/user-attachments/assets/7254df3e-a6be-49f8-bc00-74a56e6c251f)

2024-12-03 18:23 UTC, ayushsatyam146 commented
@arpitbbhayani @JyotinderSingh @gauravsarma1992 @psrvere please review

2024-12-07 17:31 UTC, JyotinderSingh requested changes
Thanks for the changes so far @ayushsatyam146. I have left a few more comments.

2024-12-09 12:23 UTC, lucifercr07 requested changes

2024-12-09 12:23 UTC, ayushsatyam146 commented on internal/wal/wal_null.go
Having the name as Null might cause readability issues as people might confuse it with some language or system specific value. Thoughts?

2024-12-09 12:29 UTC, ayushsatyam146 commented on internal/wal/wal_aof.go
> +				errCh <- fmt.Errorf("error creating segment file %s: %v", filePath, err)
File pre-allocation will entirely go away as discussed in the previous community call

2024-12-09 12:31 UTC, ayushsatyam146 commented on internal/wal/wal_aof.go
> +		fmt.Println("Found existing log segments:", files)
This is just a place holder and will be replaced with WAL Replay logic later on

2024-12-12 07:41 UTC, ayushsatyam146 commented on internal/wal/wal_aof.go
> +func (wal *WALAOF) Init(t time.Time) error {
It is not getting used but it is just there to maintain consistency with the abstract WAL Init function signature. We can remove it once we AOF WAL is stable and we don't need abstract WAL

2024-12-12 07:43 UTC, ayushsatyam146 commented on config/config.go
> +	BufferSyncInterval       time.Duration `config:"max_segment_rotation_time" default:"200ms" validate:"min=1ms"`
We had this discussion in last call and most probably time based segment rotation will discarded entirely. We can keep it like this for now and remove these things in next iteration. Thoughts @JyotinderSingh?

2024-12-12 07:44 UTC, ayushsatyam146 commented on config/config.go
> +	RotationMode             string        `config:"rotation_mode" default:"segemnt-size" validate:"oneof=segment-size time"`
Yes most probably it will be discarded. I just tried to follow design doc as closely as possible for this iteration.
cc @JyotinderSingh

2024-12-12 07:52 UTC, ayushsatyam146 commented
@JyotinderSingh @lucifercr07 I have included most of the suggested changes now. I have tried to keep the implementation as close to the design doc as possible.
However, I have left a few things because I feel like they are more related to design decisions rather than current code in the PR. In my opinion we should follow up on those things in the next iteration as this PR is getting lengthy and a bit unmanageable. We should eventually retire the abstract WAL and make AOF as the default WAL. 

Please let me know if there are other things you would like me to change. Thanks!

2024-12-16 11:11 UTC, ayushsatyam146 commented
Hi @JyotinderSingh @arpitbbhayani can you please reveiw the PR, Thanks!

2024-12-16 16:17 UTC, merged