optimize docker build
DiceDB/dice pull request #195
Opened 2024-08-01 06:56 UTC by xprgv

Decrease docker image size in ~182x times

$ docker images
dicedb/dice-server                  local             f6c14c5a0037   2 minutes ago   5.21MB
dicedb/dice-server                  latest            438e97b919ea   7 weeks ago     948MB

2024-08-01 16:30 UTC, JyotinderSingh requested changes
Thanks for the change, added some minor comments. Could you also attach a screenshot of the docker image successfully starting up and a redis client being able to connect to it?

2024-08-01 16:30 UTC, JyotinderSingh commented on Dockerfile
> +FROM golang:1.22.5 AS builder
Let's leave the go version the same as before, we should use the same version for development and deployment.

2024-08-01 16:30 UTC, JyotinderSingh commented on Dockerfile
> -EXPOSE 7379
Let's retain the `EXPOSE 7379` line

2024-08-03 13:59 UTC, JyotinderSingh commented on Dockerfile
> +FROM golang:1.22.5 AS builder
It looks like the repo's version of the dockerfile has been updated, please modify this to line up with the version in go.mod.

2024-08-06 04:08 UTC, Maveric-k07 commented
@JyotinderSingh can I wrap this up if it is inactive?

2024-08-06 04:13 UTC, JyotinderSingh commented
> @JyotinderSingh can I wrap this up if it is inactive?

Go ahead.

2024-08-06 04:14 UTC, xprgv commented
> Thanks for the change, added some minor comments. Could you also attach a screenshot of the docker image successfully starting up and a redis client being able to connect to it?

I will try to do it today

2024-08-06 04:19 UTC, xprgv commented
Sorry for long inactivity, was far away from my workstation

2024-08-06 07:55 UTC, JyotinderSingh commented
> > Thanks for the change, added some minor comments. Could you also attach a screenshot of the docker image successfully starting up and a redis client being able to connect to it?
> 
> I will try to do it today. Sorry for long inactivity, was far away from my workstation

Sure

2024-08-06 08:53 UTC, xprgv commented
> Thanks for the change, added some minor comments. Could you also attach a screenshot of the docker image successfully starting up and a redis client being able to connect to it?

![image](https://github.com/user-attachments/assets/b96834e4-8664-4956-90bf-f17e9e89b7cd)

2024-08-06 12:14 UTC, merged