feat: [GH-198] Adding unit tests for eval.go file
DiceDB/dice pull request #210
Opened 2024-08-02 19:29 UTC by lucifercr07

- Adding unit tests for `eval.go` file
- Few test cases are blocked due to [GH-201](https://github.com/DiceDB/dice/issues/201), would update once issue is resolved.

2024-08-03 13:44 UTC, lucifercr07 commented
@JyotinderSingh @yashs360 please review once.

2024-08-04 13:05 UTC, yashs360 approved these changes
lgtm; thanks for contributing

2024-08-05 17:39 UTC, JyotinderSingh commented
Could you please rebase on latest master and resolve the conflicts?

2024-08-08 19:06 UTC, lucifercr07 commented
@JyotinderSingh please review once have rebase the branch, and edited some new test case to maintain parity with `testCase` struct.

2024-08-10 10:21 UTC, JyotinderSingh requested changes
Thanks a ton for adding all these tests, have left a few small coments.

2024-08-10 10:21 UTC, JyotinderSingh commented on core/eval_test.go
> +func runTests(t *testing.T, tests map[string]testCase, evalFunc func([]string) []byte) {
Let's not use generic names for functions since they can pollute the package namespace. Maybe rename this to `runEvaltests`?

2024-08-10 10:21 UTC, JyotinderSingh commented on core/eval_test.go
>  type testCase struct {
Rename this to evalTestCase

2024-08-10 10:21 UTC, JyotinderSingh commented on core/eval_test.go
> +func teardownTest() {
This is probably not needed if you are already calling `setupTest()`

2024-08-10 10:21 UTC, JyotinderSingh commented on core/eval_test.go
> +	expires = make(map[*Obj]uint64)
You can call `RestetStore()` here instead.
I also noticed that `ResetStore()` doesn't reset the KeyspaceStat map, so please add the line below into the ResetStore function as well as a part of this PR.

2024-08-11 14:05 UTC, JyotinderSingh approved these changes
Thanks for this contribution! Approved.

2024-08-11 14:06 UTC, merged