Add support for EXAT in SET command
DiceDB/dice pull request #218
Opened 2024-08-03 11:39 UTC by colommar

## Add `EXAT` Support to `SET` Command

### Description

This pull request adds support for the `EXAT` option to the `SET` command, similar to the `EXAT` option in Redis. The `EXAT` option sets the specified Unix time at which the key will expire, in seconds.
Solving the issue #202

### Changes Made

1. **Implemented `EXAT` Option**:
   - Updated the `SET` command to handle the `EXAT` option.
   - Parsed the Unix time provided and set the key to expire at the specified time.

2. **Unit Tests**:
   - Added unit tests for the `EXAT` option to ensure correct behavior.
   - Verified that the key expires at the correct time when using `EXAT`.

3. **Integration Tests**:
   - Ported relevant integration tests from the Redis test suite in `aof_test.go`

4. **Benchmarking**:
   - Used `benchmem` to track memory allocations and optimize where necessary.

2024-08-03 16:20 UTC, arpitbbhayani commented
Hello @colommar,

This is pretty amazing PR. Thanks!
I see there are changes in go.mod file, any specific reasons for it? Also your changes led to Merge Conflicts, can you resolve them and everything looks good to be merged.

2024-08-04 12:05 UTC, lucifercr07 requested changes

2024-08-04 12:05 UTC, lucifercr07 commented on core/eval.go
> +				return Encode(errors.New("ERR invalid EXAT time in the past"), false)
This behaviour doesn't reflect the same what's done in redis. 
Redis does not reject the `EXAT` value if it is in the past. Instead, it sets the key and immediately expires it if the timestamp has already passed.
@JyotinderSingh @arpitbbhayani please correct me if I'm wrong here.

2024-08-04 12:05 UTC, lucifercr07 commented on core/eval.go
> +			exAt, err := strconv.ParseInt(args[i], 10, 64)
We also need to add positive integer check.

2024-08-04 12:05 UTC, lucifercr07 commented on core/eval.go
> +
Nit: Please remove if unintentional

2024-08-05 18:45 UTC, arpitbbhayani commented
Thanks @colommar Changes look good :) Merging them.

2024-08-05 18:45 UTC, merged