#189: Add JSON Support to where clause
DiceDB/dice pull request #300
Opened 2024-08-11 11:44 UTC by YahyaHaq

2024-08-16 06:07 UTC, JyotinderSingh requested changes
Please add the benchmarks and unit tests. You can then mark the PR ready for review.

2024-08-16 06:07 UTC, JyotinderSingh commented on core/executor.go
> +		if expr.Type == sqlparser.StrVal && strings.HasPrefix(string(expr.Val), "_") && getEncoding(row.Value.TypeEncoding) == OBJ_ENCODING_JSON && getType(row.Value.TypeEncoding) == OBJ_TYPE_JSON {
You can probably add a comment explaining why we're checking for an underscore prefix here.

2024-08-17 16:33 UTC, JyotinderSingh commented
Thanks for adding the tests @YahyaHaq. Could you please rebase your branch on the latest master to resolve the conflicts?

2024-08-17 16:35 UTC, YahyaHaq commented
Yes I'm doing that right now. Also uploading the benchmarks

On Sat, 17 Aug 2024, 9:33 pm Jyotinder Singh, ***@***.***>
wrote:

> Thanks for adding the tests @YahyaHaq <https://github.com/YahyaHaq>.
> Could you please rebase your branch on the latest master to resolve the
> conflicts?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DiceDB/dice/pull/300#issuecomment-2294907048>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APNRROZ4SFENS6X2YILBXGLZR53O7AVCNFSM6AAAAABMKV2MICVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJUHEYDOMBUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-17 19:07 UTC, JyotinderSingh approved these changes
Thanks for adding this feature @YahyaHaq, this will greatly improve the capabilities of our SQL Execution engine and make it a lot more feature-complete.
Thanks!

2024-08-17 19:41 UTC, AshwinKul28 commented
@YahyaHaq Please check the warning mentioned in the lint check and follow the instructions given to fix it. Thanks

2024-08-17 20:08 UTC, JyotinderSingh commented
> @YahyaHaq Please check the warning mentioned in the lint check and follow the instructions given to fix it. Thanks

Will merge this for now and fix the warnings myself as an exception. I am travelling tomorrow so I won't be able to check the PRs.

2024-08-17 20:08 UTC, merged

2024-08-18 06:49 UTC, YahyaHaq commented
@JyotinderSingh @arpitbbhayani Thank you so much for merging. This was a great first issue for me and I learned quite a lot about the code base. For the next steps there are some features i think would really improve DiceDB:
1. Adding support for boolean values both in JSON Querying and SET, GET operations
2. Currently whenever we want to evaluate a qwatch query we go through all the keys present and check if they match the key regex provided. I am assuming there are going to be cases where the user provides an exact key that they wants to watch. In that scenario it would be overkill to loop over all the keys stored in our keypool. How about we check that if the user has not provided regex in the key string then we do an exact match from our keypool. This might make our qwatch operation faster for this usecase
3. Fixing the QWATCH bug that i identified that integers are being returned as strings. 

Let me know what you think about these points and i will start to create PRs for these as now i have a strong idea on how to go by this

2024-08-18 07:14 UTC, JyotinderSingh commented
> @JyotinderSingh @arpitbbhayani Thank you so much for merging. This was a great first issue for me and I learned quite a lot about the code base. For the next steps there are some features i think would really improve DiceDB:
> 
> 1. Adding support for boolean values both in JSON Querying and SET, GET operations
> 
> 2. Currently whenever we want to evaluate a qwatch query we go through all the keys present and check if they match the key regex provided. I am assuming there are going to be cases where the user provides an exact key that they wants to watch. In that scenario it would be overkill to loop over all the keys stored in our keypool. How about we check that if the user has not provided regex in the key string then we do an exact match from our keypool. This might make our qwatch operation faster for this usecase
> 
> 3. Fixing the QWATCH bug that i identified that integers are being returned as strings. 
> 
> 
> 
> Let me know what you think about these points and i will start to create PRs for these as now i have a strong idea on how to go by this

Amazing to hear this @YahyaHaq! I agree, the issues you mentioned would be good next steps. Could you create the issues for (1) and (3)? (2) is a good suggestion, let's discuss further on it on our discord.

Thanks!