Feature: Add dumping store data to temp file in BGREWRITEAOF command
DiceDB/dice pull request #398
Opened 2024-08-22 19:53 UTC by ashwaniYDV

closes https://github.com/DiceDB/dice/issues/397

2024-08-23 11:54 UTC, ashwaniYDV commented
@yashs360 @JyotinderSingh please review this PR. This would guarantee that the old AOF file is not corrupted when BGREWRITEAOF happens and would improve durability.

2024-08-24 18:40 UTC, ashwaniYDV commented
@arpitbbhayani would you please review

2024-08-25 07:33 UTC, lucifercr07 requested changes

2024-08-25 07:33 UTC, lucifercr07 commented on core/aof.go
> +		fmt.Println("fsync failed")
Are these `Println` statements required? If yes shall we use `fmt. Errorf()` instead?

2024-08-31 18:41 UTC, amityahav commented
Please wait with that. I have a pr that makes this even more robust and correct

2024-09-01 13:40 UTC, ashwaniYDV commented
closing this PR.
thanks @amityahav

2024-09-01 13:40 UTC, closed without merging