adding check for controlling the max tcp connections
DiceDB/dice pull request #426
Opened 2024-08-29 17:41 UTC by ayush571995

For issue :
https://github.com/DiceDB/dice/issues/415

2024-08-30 15:26 UTC, ayush571995 commented
* The changes that are included in the PR.
  The change allows to limit the number of connections with the maxConnectionLimit

  * Design document, if any.

  * Information on any implementation choices that were made.

  * Evidence of sufficient testing. You ``MUST`` indicate the tests done, either manually or automated.
  Manual testing has been done. Ran the program with my changes and in local changed the maxConnectionLimit to 2 instead of 2000 from the config file. Created multiple connections from terminal and post the limit breach we are logging at server
```
        2024/08/30 20:51:43 INFO Password
        2024/08/30 20:51:43 INFO default user set up password required=false
        2024/08/30 20:52:16 WARN connection refused. Reached the max-connection limit
```
At client we close the connection with at terminal 
```
        truesaiyan@Asus-Rog-G15:~/oss/dicedb/dice$ dice -h localhost -p 7379
        Error while reading from localhost:7379 : (104, 'Connection reset by peer')
```

2024-09-01 09:14 UTC, JyotinderSingh commented
Thanks for the PR, please add test cases verifying the functionality.

2024-09-01 09:53 UTC, ayush571995 commented
@JyotinderSingh The test cases are a little tricky here as I don't feel we should make 20k connections in integration test
These20k connections limit needs to be changed and would require change how we create async server . We need a new GetAsyncServer for testing and there we can hardcode the limit to some lower number and that is something which we should control with a flag 


So all these changes would be required

2024-09-03 06:15 UTC, JyotinderSingh commented
> @JyotinderSingh The test cases are a little tricky here as I don't feel we should make 20k connections in integration test These20k connections limit needs to be changed and would require change how we create async server . We need a new GetAsyncServer for testing and there we can hardcode the limit to some lower number and that is something which we should control with a flag
> 
> So all these changes would be required

Yeah, that makes sense. We could launch a new server as a part of a separate test suite to allow ourselves to test such configuration-related behavior.

Additionally, we should be handling some additional edge cases, [similar to what redis does](https://redis.io/docs/latest/develop/reference/clients/#:~:text=Maximum%20Concurrent%20Connected%20Clients&text=The%20default%20is%2010%2C000%20clients,the%20soft%20limit%20is%20checked)

2024-09-06 18:42 UTC, lucifercr07 commented
@ayush571995 please rebase to resolve conflicts.

2024-09-12 15:06 UTC, lucifercr07 commented
@ayush571995 please check once the builds are failing.

2024-09-12 17:46 UTC, JyotinderSingh commented
@ayush571995 Are you actively working on this?

2024-09-12 17:50 UTC, ayush571995 commented
> @ayush571995 Are you actively working on this?

Yes but I need some suggestions
How can we connect ?

2024-09-15 10:37 UTC, ayush571995 commented
@JyotinderSingh Added test can you please review ?

2024-09-17 19:51 UTC, JyotinderSingh requested changes
Thanks for the changes. Left a few comments.

Also, we now have a server directory under `integration_tests/` directory. There you can create a new server and pass in the required config using the regular APIs. Please refer to the existing tests for this.

2024-09-17 19:51 UTC, JyotinderSingh commented on config/test_config.go
We probably don't need this, you can set the config values as a part of the test.

2024-09-17 19:51 UTC, JyotinderSingh commented on internal/server/server.go
> +
We shouldn't need to define a new method like this.

2024-09-24 16:28 UTC, lucifercr07 commented
@ayushsatyam146 please resolve the conflicts.

2024-09-25 02:47 UTC, ayushsatyam146 commented
I think you tagged the wrong Ayush @lucifercr07 😅

2024-09-26 11:13 UTC, ayush571995 commented on integration_tests/server/max_conn_test.go
> +var maxConnTestOptions = commands.TestServerOptions{
Done

2024-09-26 11:13 UTC, ayush571995 commented on integration_tests/server/max_conn_test.go
> +		time.Sleep(500 * time.Millisecond)
Removed

2024-09-26 11:14 UTC, ayush571995 commented on integration_tests/server/max_conn_test.go
> +	time.Sleep(1 * time.Second)
Removed

2024-09-26 11:14 UTC, ayush571995 commented on config/test_config.go
Sure will do that

2024-09-26 11:16 UTC, ayush571995 commented
@JyotinderSingh @lucifercr07 
Made the changes can you guys have a look .

2024-09-29 18:00 UTC, lucifercr07 approved these changes
LGTM, thanks for contributing.

2024-09-29 18:00 UTC, lucifercr07 commented on internal/server/server.go
> +	if len(s.connectedClients) > s.maxClients {
Ideally it's not a good practice have same number of maxClients value as the backlog queue max number which is being set during `listen()`. Shouldn't be a blocker for this PR, but we should revisit this later.

2024-09-29 18:01 UTC, merged