Nijin p s/json forget
DiceDB/dice pull request #524
Opened 2024-09-10 16:39 UTC by Nijin-P-S

Implementation for Issue : [495](https://github.com/DiceDB/dice/issues/494)

- Add JSON.FORGET command implementation , refer : [JSON.FORGET](https://redis.io/docs/latest/commands/json.forget/)
- Add Unit Test for JSON.FORGET 
- Add Integration Test for JSON.FORGET

Attaching below the screenshots of behavior of:
**1. JSON.FORGET command in Redis:**

<img width="1527" alt="Screenshot 2024-09-10 at 9 59 44 PM" src="https://github.com/user-attachments/assets/80fd64b8-b9b1-419d-8446-20df154fb05d">

**2. JSON.FORGET command in dice**
![Uploading Screenshot 2024-09-10 at 9.59.50 PM.png…]()

2024-09-10 16:56 UTC, kushal0511-not commented
Thanks for contributing @Nijin-P-S .
I see JSON.FORGET is just alias of JSON.DEL command in docs. So instead of writing same code again can we just call JSON.DEL command inside it.wdyt?
Correct if me i am missing something.

2024-09-10 17:02 UTC, Nijin-P-S commented
Yes @kushal0511-not ,
That should work, as JSON.FORGET is just used for deletion of a single path and JSON.DEL can be used for bulk deletion.
Calling the DEL function inside the JSON.FORGET would be better. Let me make the changes necessary and remove the excessive code.

2024-09-10 17:19 UTC, Nijin-P-S commented
@kushal0511-not ,
Have updated the implementation to call the evalJSONDEL() thus reducing the code repeatation. 
Cross verified the unit tests, Integration tests and functionality, and is working as expected.

Attaching the screenshots:
1. Unit Tests
<img width="1527" alt="Screenshot 2024-09-10 at 10 41 22 PM" src="https://github.com/user-attachments/assets/a741234f-c88c-47b2-b7df-be615e81a0a7">

2. Integration Test
<img width="1527" alt="Screenshot 2024-09-10 at 10 41 48 PM" src="https://github.com/user-attachments/assets/6f316bce-73a8-4e10-9211-057c7b748ef9">

3. Functionality
<img width="1527" alt="Screenshot 2024-09-10 at 10 44 51 PM" src="https://github.com/user-attachments/assets/0865772c-c9df-426e-97e9-3bc8277b6d38">


Let me know if anything needs to be modified or added.

Thanks.

2024-09-10 17:33 UTC, kushal0511-not commented on internal/eval/eval.go
> +	// Default path is root if not specified
nit: Consider aligning the comment with the code for better readability.

2024-09-10 17:40 UTC, Nijin-P-S commented
@kushal0511-not ,
Made the changes.

Thanks.

2024-09-11 13:39 UTC, lucifercr07 requested changes
@Nijin-P-S thanks for contributing, have minor comment. Please review once.

2024-09-11 13:39 UTC, lucifercr07 commented on internal/eval/eval.go
> +    key := args[0]
Can we just change L341 to L349 to return `evalJSONDEL(args, store)`?

2024-09-12 15:02 UTC, merged