added JSON.INGEST support for HTTP
DiceDB/dice pull request #588
Opened 2024-09-15 08:52 UTC by kushal0511-not

Added JSON.INGEST support.
![Screenshot from 2024-09-15 14-14-54](https://github.com/user-attachments/assets/0618a43d-ddaa-4ea8-9819-edf34ce8bbff)

![Screenshot from 2024-09-15 14-16-04](https://github.com/user-attachments/assets/16d20889-9d44-4f58-bdc1-ababeab4935b)

![Screenshot from 2024-09-15 14-16-26](https://github.com/user-attachments/assets/43728bd6-1cca-4d3f-9d40-7daf9b550a86)

What is remaining: 

- unit tests
- documentation

2024-09-15 09:12 UTC, kushal0511-not commented
@JyotinderSingh please review this draft PR.
 If changes look good, I will add unit test cases for command.

2024-09-17 10:55 UTC, lucifercr07 requested changes

2024-09-17 10:55 UTC, lucifercr07 commented on internal/eval/eval.go
> +	store.Put(generatedKey, newObj)
Please correct me if I'm missing something, can we not use a call to `JSONSET` here?

2024-09-17 10:55 UTC, lucifercr07 commented on internal/eval/eval.go
> +	uniqueID := uuid.New()
Not sure if we required a 128 bits uuid for this. May be we can use some other lib here.

2024-09-17 13:25 UTC, lucifercr07 reviewed
LGTM, please make the PR ready for review to approve.

2024-09-17 15:27 UTC, kushal0511-not commented
@lucifercr07 Thanks for reviewing.
I have made it ready for review.
I have one question , do i need to include any unit testcase for this command(HTTP protocol )  under this issue? if yes, what should be the most suitable location for that.
Or  test cases will be covered in https://github.com/DiceDB/dice/issues/558 or https://github.com/DiceDB/dice/issues/552

2024-09-17 17:17 UTC, kushal0511-not commented
@lucifercr07 Thanks for reviewing.
Resolved conflicts.

2024-09-17 20:02 UTC, pratikpandey21 commented
Small recommendation, but I think it might make sense to return the generated ID as response, rather than OK. @kushal0511-not

2024-09-18 01:45 UTC, kushal0511-not commented
Changes done @pratikpandey21.
Please review  it.

2024-09-18 04:57 UTC, lucifercr07 approved these changes

2024-09-18 09:36 UTC, merged