#622: Add ECHO command
DiceDB/dice pull request #626
Opened 2024-09-19 18:57 UTC by hgupta12

Resolves #622 : Add support for ECHO command.

## Description
This  PR adds support for [ECHO](https://redis.io/docs/latest/commands/echo/) command to DiceDB.
Added unit tests (internal/eval/eval_test.go)

## Screenshots
![image](https://github.com/user-attachments/assets/4a3c231e-2434-434b-a649-f6ff38ba0fad)

2024-09-20 15:27 UTC, apoorvyadav1111 requested changes

2024-09-20 15:27 UTC, apoorvyadav1111 commented on internal/eval/commands.go
> +		KeySpecs: KeySpecs{BeginIndex: 1},
Hi, for commands with arguments without keys, we can omit KeySpecs.

2024-09-20 15:27 UTC, apoorvyadav1111 commented on internal/eval/eval.go
> +	return b
nit:
```suggestion
	return clientio.Encode(args[0], false)
```

2024-09-20 15:28 UTC, apoorvyadav1111 commented
Hi, thanks for adding this feature. I left some minor comments.

2024-09-20 18:07 UTC, hgupta12 commented
@apoorvyadav1111 I have resolved the comments.

2024-09-20 18:24 UTC, apoorvyadav1111 approved these changes

2024-09-21 05:39 UTC, lucifercr07 approved these changes

2024-09-21 05:39 UTC, merged